version: "3.9"
services:
  documents_service:
    image: qwerrty574/msa_documents_service:latest
    ports:
      - "8081:80"
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 80 --reload"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/__health" ]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 5s
    restart: on-failure

  krakend:
    image: devopsfaith/krakend
    volumes:
      - "./config/krakend:/etc/krakend"
    ports:
      - "8080:8080"
    command: [ "run", "-d", "--config", "/etc/krakend/krakend.json" ]
    depends_on:
      documents_service:
        condition: service_healthy

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - krakend

  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana/datasources:/etc/grafana/provisioning/datasources
    restart: unless-stopped